cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  image: golang:1-buster
  script:
    - apt update
    - apt install -y --no-install-recommends libmagickwand-dev imagemagick libmagickwand-6-headers libmagickcore-dev
    - go run main.go
    - mkdir dist
    - mv index.html dist/
    - mv previews/ dist/
    - mv talks/ dist/
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  image: node:12-alpine
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
  only:
    - master
